// Kontrollitud.ee/frontend/src/icons.js
// Централизованная библиотека иконок FontAwesome для Tree Shaking

import { library } from '@fortawesome/fontawesome-svg-core';

// Импортируем только используемые solid иконки
import {
  faList,
  faHandshake,
  faNewspaper,
  faPlusCircle,
  faSignInAlt,
  faChevronDown,
  faShieldAlt,
  faClipboardList,
  faSignOutAlt,
  faStar,
  faStarHalfAlt,
  faArrowLeft,
  faCheckCircle,
  faShareAlt,
  faMapMarkerAlt,
  faInfoCircle,
  faPhone,
  faEnvelope,
  faGlobe,
  faDirections,
  faClock,
  faChartBar,
  faCommentDots,
  faLock,
  faUser,
  faComment,
  faSpinner,
  faPaperPlane,
  faExclamationCircle,
  faSearch,
  faSpa,
  faUtensils,
  faShoppingBag,
  faChild,
  faPlane,
  faCar,
  faCogs,
  faSearchLocation,
  faComments,
  faUserCheck,
  faTimes,
  faArrowRight,
  faTachometerAlt,
  faCalendarAlt,
  faEdit,
  faTrash,
  faEye,
  faHourglassHalf,
  faTimesCircle,
  faCalendar,
  faArrowDown,
  faCrown,
  faBolt,
  faRocket,
  faBan,
  faSave,
  faImage,
  faCloudUploadAlt,
  faTag,
  faCheck,
  faBuilding,
  faDownload,
  faShare,
  faPlusSquare,
  faHome,
  faInbox,
} from '@fortawesome/free-solid-svg-icons';

// Импортируем regular иконки
import {
  faStar as faStarRegular,
} from '@fortawesome/free-regular-svg-icons';

// Импортируем brands иконки
import {
  faInstagram,
  faTiktok,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

// Добавляем все иконки в библиотеку
library.add(
  // Solid icons
  faList,
  faHandshake,
  faNewspaper,
  faPlusCircle,
  faSignInAlt,
  faChevronDown,
  faShieldAlt,
  faClipboardList,
  faSignOutAlt,
  faStar,
  faStarHalfAlt,
  faArrowLeft,
  faCheckCircle,
  faShareAlt,
  faMapMarkerAlt,
  faInfoCircle,
  faPhone,
  faEnvelope,
  faGlobe,
  faDirections,
  faClock,
  faChartBar,
  faCommentDots,
  faLock,
  faUser,
  faComment,
  faSpinner,
  faPaperPlane,
  faExclamationCircle,
  faSearch,
  faSpa,
  faUtensils,
  faShoppingBag,
  faChild,
  faPlane,
  faCar,
  faCogs,
  faSearchLocation,
  faComments,
  faUserCheck,
  faTimes,
  faArrowRight,
  faTachometerAlt,
  faCalendarAlt,
  faEdit,
  faTrash,
  faEye,
  faHourglassHalf,
  faTimesCircle,
  faCalendar,
  faArrowDown,
  faCrown,
  faBolt,
  faRocket,
  faBan,
  faSave,
  faImage,
  faCloudUploadAlt,
  faTag,
  faCheck,
  faBuilding,
  faDownload,
  faShare,
  faPlusSquare,
  faHome,
  faInbox,
  // Regular icons
  faStarRegular,
  // Brands icons
  faInstagram,
  faTiktok,
  faYoutube
);

// Экспортируем все иконки для прямого использования (опционально)
export {
  // Solid
  faList,
  faHandshake,
  faNewspaper,
  faPlusCircle,
  faSignInAlt,
  faChevronDown,
  faShieldAlt,
  faClipboardList,
  faSignOutAlt,
  faStar,
  faStarHalfAlt,
  faArrowLeft,
  faCheckCircle,
  faShareAlt,
  faMapMarkerAlt,
  faInfoCircle,
  faPhone,
  faEnvelope,
  faGlobe,
  faDirections,
  faClock,
  faChartBar,
  faCommentDots,
  faLock,
  faUser,
  faComment,
  faSpinner,
  faPaperPlane,
  faExclamationCircle,
  faSearch,
  faSpa,
  faUtensils,
  faShoppingBag,
  faChild,
  faPlane,
  faCar,
  faCogs,
  faSearchLocation,
  faComments,
  faUserCheck,
  faTimes,
  faArrowRight,
  faTachometerAlt,
  faCalendarAlt,
  faEdit,
  faTrash,
  faEye,
  faHourglassHalf,
  faTimesCircle,
  faCalendar,
  faArrowDown,
  faCrown,
  faBolt,
  faRocket,
  faBan,
  faSave,
  faImage,
  faCloudUploadAlt,
  faTag,
  faCheck,
  faBuilding,
  faDownload,
  faShare,
  faPlusSquare,
  faHome,
  faInbox,
  // Regular
  faStarRegular,
  // Brands
  faInstagram,
  faTiktok,
  faYoutube,
};

export default library;
